### ISSUE TITLE
Develop a functional test suite

### ISSUE THREAD

**Issue by evan2645** [spiffe/spiffe-csi#4]
We want to make sure that the container builds and the driver works as expected on a regular basis. We also want to be sure that it is working with the currently supported versions of Kubernetes.

I am not sure the best way to accomplish this. I found [this blog post](https://kubernetes.io/blog/2020/01/08/testing-of-csi-drivers/) about using a utility to test CSI drivers. At a minimum, the test should ensure that the container can launch and perform the intended function.

**Comment by azdagron** [comment]
We've had integration tests for a while. Recently merged #19 which expands the test suite to test many K8s versions.
